# Generated by Django 3.2.8 on 2021-10-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('last_scraped', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=200)),
                ('author_status', models.CharField(max_length=50)),
                ('author_role', models.CharField(max_length=50)),
                ('author_location', models.CharField(max_length=50)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraping.platform')),
            ],
        ),
    ]
