# Generated by Django 3.2.8 on 2021-10-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='total_rating_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2500)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.review')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(max_length=100)),
                ('rating_score', models.DecimalField(decimal_places=2, max_digits=2)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.review')),
            ],
        ),
    ]
