# Generated by Django 3.2.8 on 2021-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_review_author_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='total_rating_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
