# Generated by Django 3.2.8 on 2021-11-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_alter_review_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='creation_date',
        ),
    ]
