# Generated by Django 3.2.8 on 2021-10-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('author_status', models.CharField(max_length=50)),
                ('author_role', models.CharField(max_length=50)),
                ('author_location', models.CharField(max_length=50)),
            ],
        ),
    ]
