# Generated by Django 3.2.8 on 2021-10-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
