# Generated by Django 3.2.8 on 2021-10-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indeed', '0002_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='url',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
